/* ============ DATA ============ */
var FEATURES = [
  {ic:"🚨", t:{id:"Peringatan Kerugian dalam Dolar",en:"Loss Warnings in Dollars"},
   id:"Sebelum swap, Freesia menghitung berapa uang yang akan hilang — bukan cuma persen. Kalau angkanya buruk, tombolnya berubah dan Anda harus mengetik konfirmasi. Kami menahan, bukan melarang.",
   en:"Before a swap, Freesia works out how much money you'd lose — not just a percentage. When the number is bad, the button changes and you must type a confirmation. We slow you down; we never block you."},
  {ic:"🛡️", t:{id:"Pemeriksaan Keamanan Swap",en:"Swap Safety Check"},
   id:"Setiap swap dirangkum jadi satu vonis: aman, hati-hati, atau berisiko — memakai dampak harga dan pembanding oracle DIA.",
   en:"Every swap is summarised into one verdict: safe, caution, or risky — using price impact and the DIA oracle benchmark."},
  {ic:"🔍", t:{id:"Kuotasi On-Chain",en:"On-Chain Quotes"},
   id:"Estimasi hasil swap dihitung langsung dari smart contract, bukan simulasi off-chain. Sesaat sebelum kirim, kutipan diambil ulang agar transaksi tidak gagal sia-sia.",
   en:"Swap estimates come straight from the smart contract, not an off-chain simulation. Right before sending, the quote is refetched so your transaction doesn't fail for nothing."},
  {ic:"💧", t:{id:"Add / Remove Liquidity",en:"Add / Remove Liquidity"},
   id:"Sediakan likuiditas ke pool USDC/DAI, KOPDES/USDC, atau MBG/USDC — dan tarik kembali kapan saja, langsung on-chain.",
   en:"Provide liquidity to the USDC/DAI, KOPDES/USDC, or MBG/USDC pools — and withdraw anytime, fully on-chain."},
  {ic:"🌱", t:{id:"Stake LP, Earn FREE",en:"Stake LP, Earn FREE"},
   id:"Stake LP token Anda untuk menghasilkan reward FREE dalam periode yang jelas — bukan janji imbal hasil tanpa batas.",
   en:"Stake your LP tokens to earn FREE rewards over a clearly bounded period — not a promise of infinite yield."},
  {ic:"📉", t:{id:"Kalkulator Impermanent Loss",en:"Impermanent Loss Calculator"},
   id:"Geser satu slider dan lihat kerugian Anda dibanding sekadar menahan token — sebelum jadi LP, bukan sesudah menyesal.",
   en:"Drag one slider and see your loss versus simply holding — before you become an LP, not after you regret it."},
  {ic:"📊", t:{id:"Statistik & Peringkat On-Chain",en:"On-Chain Stats & Leaderboard"},
   id:"Dashboard dan peringkat dihitung dari event Swap di kontrak, bukan data browser. Saat sepi, angkanya ditampilkan apa adanya — tidak dipoles.",
   en:"The dashboard and leaderboard are computed from contract Swap events, not browser data. When it's quiet, the numbers say so — unpolished."},
  {ic:"🕐", t:{id:"Riwayat Transaksi On-Chain",en:"On-Chain Transaction History"},
   id:"Riwayat swap dibaca dari event milik alamat Anda langsung di kontrak — bertahan setelah halaman ditutup, dan bisa diperiksa di explorer.",
   en:"Your swap history is read from your address's own contract events — it survives a page reload and can be checked on the explorer."},
  {ic:"🚰", t:{id:"Testnet Faucet",en:"Testnet Faucet"},
   id:"Klaim token testnet gratis langsung dari DEX. Tanpa daftar, tanpa izin, tanpa syarat.",
   en:"Claim free testnet tokens directly from the DEX. No signup, no permission, no conditions."},
  {ic:"🔗", t:{id:"Koneksi Wallet Native",en:"Native Wallet Connection"},
   id:"Sambungkan wallet apa pun (MetaMask, Rabby, Zerion) lewat standar EIP-6963 — Anda yang memilih, bukan kami.",
   en:"Connect any wallet (MetaMask, Rabby, Zerion) via the EIP-6963 standard — you pick it, not us."},
  {ic:"📈", t:{id:"Grafik Dampak Harga",en:"Price Impact Chart"},
   id:"Grafik jujur: menunjukkan seberapa buruk harga Anda saat ukuran swap membesar, dihitung dari cadangan pool nyata.",
   en:"An honest chart: it shows how much worse your price gets as the swap grows, computed from real pool reserves."},
  {ic:"🕶️", t:{id:"Shielded Swap (Segera)",en:"Shielded Swap (Soon)"},
   id:"Proteksi MEV terhadap sandwich attack. BELUM AKTIF — butuh private relay atau perubahan kontrak, masih di roadmap. Kami mencantumkannya sebagai rencana, bukan fitur.",
   en:"MEV protection against sandwich attacks. NOT ACTIVE — it needs a private relay or contract changes, still on the roadmap. We list it as a plan, not a feature."},
];

var TOK = [
  {t:{id:"Fee 0.3% — 100% ke LP",en:"0.3% Fee — 100% to LPs"},
   id:"Saat ini seluruh fee swap mengalir ke penyedia likuiditas, bukan ke protokol. Kami memprioritaskan menarik likuiditas dulu, bukan mengambil untung dari pengguna awal.",
   en:"Right now, all swap fees flow to liquidity providers, not the protocol. We prioritize attracting liquidity first, not profiting from early users."},
  {t:{id:"Fee-Switch: Siap, Sengaja Dimatikan",en:"Fee-Switch: Ready, Deliberately Off"},
   id:"Infrastruktur protocol-fee sudah dirancang (maksimal 1/6 dari fee, meniru Uniswap) tapi dimatikan default. Baru diaktifkan lewat governance saat likuiditas cukup dalam — punya sakelar bukan berarti menyalakannya.",
   en:"Protocol-fee infrastructure is designed (max 1/6 of fees, mirroring Uniswap) but off by default. Only enabled via governance once liquidity is deep enough — having the switch doesn't mean flipping it."},
  {t:{id:"Treasury dari Insentif Ekosistem",en:"Treasury from Ecosystem Incentives"},
   id:"Keberlanjutan awal berasal dari dukungan ekosistem LitVM (grant, kredit audit), bukan dari memeras fee pengguna saat komunitas masih kecil.",
   en:"Early sustainability comes from LitVM ecosystem support (grants, audit credits), not from squeezing user fees while the community is small."},
  {t:{id:"Reward FREE dengan Periode Jelas",en:"FREE Rewards, Clearly Bounded"},
   id:"Reward staking berjalan dalam periode terbatas waktu yang transparan — bukan janji imbal hasil tak terbatas yang tidak berkelanjutan.",
   en:"Staking rewards run in transparent, time-bounded periods — not unsustainable promises of infinite yield."},
];

/* ===== ROADMAP (terbaru dengan AI Vault) ===== */
var ROADMAP = [
  {p:"Fase 1", t:{id:"Fondasi",en:"Foundation"}, f:"AMM Swap + Pool + Earn",
   id:"AMM constant-product lengkap: swap, penyediaan likuiditas, staking LP, dan reward FREE. Sudah berjalan dan bisa diverifikasi on-chain.",
   en:"Complete constant-product AMM: swap, liquidity provision, LP staking, and FREE rewards. Live and verifiable on-chain.",
   tId:"Selesai", tEn:"Done", active:true},
  {p:"Fase 2", t:{id:"Lapisan Perlindungan",en:"Protection Layer"}, f:"Panel Risiko + Harga DIA + Pemeriksaan Keamanan",
   id:"Fitur yang menerjemahkan risiko jadi bahasa manusia: panel kerugian dalam dolar, harga referensi oracle DIA, dan pemeriksaan keamanan swap sebelum konfirmasi. Sudah live.",
   en:"Features that translate risk into plain language: a loss panel in dollars, DIA oracle reference pricing, and a swap safety check before you confirm. Live now.",
   tId:"Selesai", tEn:"Done", active:true},
  {p:"Fase 3", t:{id:"Transparansi & Edukasi",en:"Transparency & Education"}, f:"Halaman Verifikasi + Catatan Insiden + Kalkulator IL",
   id:"Halaman verifikasi yang memeriksa tiap kontrak langsung dari rantai, catatan insiden yang menerbitkan kesalahan kami sendiri, dan kalkulator impermanent loss. Sudah live — dokumentasi publik masih berjalan.",
   en:"A verification page that checks every contract straight from the chain, an incident log that publishes our own mistakes, and an impermanent-loss calculator. Live — public docs still in progress.",
   tId:"Berjalan", tEn:"In progress", active:true},
  {p:"Fase 4", t:{id:"Eksperimen AI Vault",en:"AI Vault Experiment"}, f:"Prototipe ERC-4626 + Agen Alokasi",
   id:"Vault eksperimental tempat strategi alokasi likuiditas dihitung oleh agen AI. Masih prototipe testnet: kode tersedia untuk diperiksa, tapi belum diaudit dan belum terbukti di pasar nyata. Bisa berubah total atau dihapus kapan saja.",
   en:"An experimental vault where liquidity allocation strategy is computed by an AI agent. Still a testnet prototype: code is open for inspection, but not audited and unproven in real markets. May change completely or be removed at any time.",
   tId:"Prototipe", tEn:"Prototype", active:true},
  {p:"Fase 5", t:{id:"Kesiapan Mainnet",en:"Mainnet Readiness"}, f:"Audit + Migrasi Pool Lama + Verifikasi Kontrak",
   id:"Audit smart-contract profesional (mengandalkan dukungan ekosistem LitVM), migrasi pool USDC/DAI generasi awal ke V3, bug bounty saat dana memungkinkan, dan verifikasi kode sumber publik. Gerbang wajib sebelum mainnet.",
   en:"A professional smart-contract audit (relying on LitVM ecosystem support), migrating the early-generation USDC/DAI pool to V3, a bug bounty when funds allow, and public source verification. The required gate before mainnet.",
   tId:"Tergantung dukungan", tEn:"Support-dependent", active:false},
  {p:"Fase 6", t:{id:"Pertumbuhan Berkelanjutan",en:"Sustainable Growth"}, f:"Pair Baru + Fee-Switch + Trading Otomatis",
   id:"Arah jangka panjang: pasangan token baru (mis. zkLTC), aktivasi fee-switch protokol saat likuiditas cukup dalam, governance komunitas, serta fitur trading otomatis (DCA & Zap). Aspirasional — DCA/Zap butuh prasyarat: pengguna aktif, audit selesai, dan infrastruktur eksekusi. Tidak dibangun sebelum fondasi itu ada.",
   en:"Long-term direction: new token pairs (e.g. zkLTC), activating the protocol fee-switch once liquidity is deep enough, community governance, plus automated trading (DCA & Zap). Aspirational — DCA/Zap require prerequisites: active users, a completed audit, and execution infrastructure. Not built before that foundation exists.",
   tId:"Aspirasional", tEn:"Aspirational", active:false},
];

var SECURITY = [
  {ic:"🔒", t:{id:"Audit Mandiri Terbuka — Kontrak V3",en:"Open Self-Audit — V3 Contract"},
   d:{id:"Kontrak SimpleLiquidityPoolV3 menutup enam kelas kerentanan: setoran kecil yang lenyap, serangan first-depositor, token sisa tak dikembalikan, proteksi slippage saat penarikan, reentrancy, dan transfer gagal diam-diam. Pool KOPDES/USDC dan MBG/USDC lahir dari kontrak ini. Jujur: pool USDC/DAI dibuat sebelum V3 ada — sebagian FIX tidak bisa kami verifikasi di sana, dan migrasinya tercatat terbuka di catatan insiden.",
      en:"The SimpleLiquidityPoolV3 contract closes six vulnerability classes: vanishing small deposits, the first-depositor attack, unreturned excess tokens, slippage protection on withdrawal, reentrancy, and silent failed transfers. The KOPDES/USDC and MBG/USDC pools are born from it. Honestly: the USDC/DAI pool predates V3 — some fixes can't be verified there, and its migration is logged openly in our incident log."}},
  {ic:"🕵️", t:{id:"Kami Menerbitkan Kesalahan Kami",en:"We Publish Our Own Mistakes"},
   d:{id:"Kelemahan XSS yang kami temukan sendiri, enam kontrak yang harus dibuang, klaim yang dulu terlalu jauh — semuanya tercatat lengkap dengan akibatnya. Termasuk satu insiden yang masih terbuka hari ini.",
      en:"An XSS weakness we found ourselves, six contracts we had to discard, a claim that once reached too far — all logged, each with what it cost. Including one incident still open today."}},
  {ic:"📊", t:{id:"Harga Referensi DIA",en:"DIA Reference Pricing"},
   d:{id:"Terintegrasi dengan DIA, oracle resmi LitVM. Harga pasar independen ditampilkan di samping harga pool, agar Anda tahu bila swap tidak wajar. Oracle hanya dipakai sebagai pembanding — tidak pernah menyentuh logika swap.",
      en:"Integrated with DIA, LitVM's official oracle. Independent market prices sit next to pool prices, so you know when a swap is off. The oracle is only a benchmark — it never touches swap logic."}},
  {ic:"⚠️", t:{id:"Audit Profesional: Belum Ada",en:"Professional Audit: Not Yet"},
   d:{id:"Belum diaudit pihak ketiga. Audit mandiri kami sendiri menemukan kerentanan yang lolos berbulan-bulan — jadi kami tahu persis batasnya. Audit profesional adalah syarat mutlak sebelum mainnet. Sampai saat itu: token testnet saja.",
      en:"No third-party audit. Our own self-audit found a vulnerability that had survived for months — so we know exactly its limits. A professional audit is an absolute prerequisite before mainnet. Until then: testnet tokens only."}},
];

var FAQ = {
  id:[
    {q:"Bagaimana saya tahu Freesia tidak menipu?", a:"Jangan percaya kami — periksa sendiri. Halaman verifikasi membuat browser Anda menghubungi RPC LitVM dan membaca tiap kontrak langsung dari blockchain, tanpa melewati server kami. Halaman catatan insiden memuat daftar kesalahan kami sendiri, termasuk satu yang masih terbuka. Kalau ada yang tidak cocok, itu akan terlihat di sana, bukan di kalimat pemasaran."},
    {q:"Apakah Freesia DEX sudah live di mainnet?", a:"Belum. Saat ini Freesia DEX masih dalam fase testnet di LitVM. Mainnet baru masuk akal setelah audit profesional selesai dan pool generasi awal dimigrasikan."},
    {q:"Siapa yang membangun Freesia DEX?", a:"Satu orang: Zack. Itu berarti kesalahan akan terjadi — dan sudah terjadi. Yang kami janjikan bukan kesempurnaan, tapi Anda akan selalu tahu: semuanya kami terbitkan di catatan insiden."},
    {q:"Kapan mainnet launch?", a:"Tidak ada tanggal. Ada syarat: audit profesional selesai, pool USDC/DAI generasi awal dimigrasikan ke V3, dan ada pengguna nyata yang mengujinya. Memberi tanggal palsu lebih mudah daripada memenuhi syarat — kami memilih yang kedua."},
    {q:"Apakah smart contract sudah diaudit?", a:"Belum oleh pihak ketiga — dan sejujurnya, di fase testnet LitVM saat ini belum ada DEX yang diaudit pihak ketiga, termasuk yang terbesar. Bedanya ada pada cara mengakuinya. Sebagian proyek menyebut kontraknya 'teruji-tempur' atau 'fork dari standar industri'; itu terdengar seperti audit, padahal artinya kode itu belum pernah diperiksa untuk proyek mereka. Kami memilih menyebutnya apa adanya: belum diaudit. Yang kami lakukan adalah audit mandiri terbuka dan menulis SimpleLiquidityPoolV3 yang menutup enam kelas kerentanan (pool KOPDES/USDC dan MBG/USDC lahir dari kontrak itu). Tapi audit mandiri bukan pengganti audit profesional — audit mandiri kami sendiri sempat melewatkan kerentanan XSS berbulan-bulan. Audit profesional adalah syarat mutlak sebelum mainnet. Sampai saat itu: token testnet saja, dan Anda bisa memeriksa tiap kontrak sendiri di /verify."},
    {q:"Bagaimana cara menjadi early tester?", a:"Langsung saja pakai — token testnet gratis lewat faucet, tanpa daftar. Lalu beri tahu kami apa yang rusak di X/Twitter @0xzackbh. Laporan dari luar akan dicatat di halaman insiden lengkap dengan kredit."},
    {q:"Apakah ada token?", a:"Belum ada token yang diluncurkan, dan kami tidak terburu-buru. Token hanya masuk akal kalau ada volume nyata yang membenarkannya — meluncurkan token sebelum ada guna adalah jebakan umum. Leaderboard kami sengaja tidak menjanjikan alokasi apa pun. Fokus sekarang: fee yang adil (100% ke LP) dan keberlanjutan dari dukungan ekosistem."},
    {q:"Apakah Freesia sesuai syariah?", a:"Freesia dirancang dengan prinsip menghindari riba: imbal hasil datang dari fee atas aktivitas swap nyata, bukan bunga atas pinjaman, dan kami berkomitmen tidak menambahkan lending berbunga. Tapi jujur — kami BELUM ditinjau otoritas fiqih mana pun, jadi kami tidak menyebut diri 'bersertifikat syariah'. Sebagian ulama juga masih memperdebatkan status penyediaan likuiditas AMM. Yang kami tawarkan adalah prinsip desain yang bisa Anda periksa sendiri, dan undangan terbuka bagi ahli fiqih muamalah untuk meninjau kontrak kami. Untuk keputusan pribadi, konsultasikan ahli yang Anda percaya."},
    {q:"Apa itu AI Vault?", a:"AI Vault adalah prototipe eksperimental ERC-4626 tempat agen AI menghitung alokasi likuiditas. Masih fase testnet: kodenya terbuka, tapi belum diaudit dan belum terbukti di pasar nyata. Bisa berubah total atau dihapus kapan saja. Jangan anggap ini produk jadi."},
  ],
  en:[
    {q:"How do I know Freesia isn't a scam?", a:"Don't trust us — check. The verification page makes your own browser contact the LitVM RPC and read each contract straight from the blockchain, never through our servers. The incident log lists our own mistakes, including one still open. If something doesn't add up, it'll show up there, not in a marketing sentence."},
    {q:"Is Freesia DEX live on mainnet?", a:"Not yet. Freesia DEX is currently in testnet phase on LitVM. Mainnet only makes sense after a professional audit and after the early-generation pool is migrated."},
    {q:"Who is building Freesia DEX?", a:"One person: Zack. That means mistakes will happen — and they have. What we promise isn't perfection; it's that you'll always know: everything gets published in the incident log."},
    {q:"When is mainnet launch?", a:"No date. There are conditions: a completed professional audit, migrating the early-generation USDC/DAI pool to V3, and real users testing it. Announcing a fake date is easier than meeting conditions — we chose the latter."},
    {q:"Are the smart contracts audited?", a:"Not by a third party — and honestly, at LitVM's current testnet stage no DEX is third-party audited, including the largest ones. The difference is how you admit it. Some projects call their contracts 'battle-tested' or 'forked from industry standards'; that sounds like an audit, but it means the code was never reviewed for their project. We'd rather say it plainly: not audited. What we did do is an open self-audit and wrote SimpleLiquidityPoolV3, which closes six vulnerability classes (the KOPDES/USDC and MBG/USDC pools are born from it). But a self-audit is no substitute for a professional one — ours missed an XSS weakness for months. A professional audit is a hard prerequisite before mainnet. Until then: testnet tokens only, and you can check every contract yourself at /verify."},
    {q:"How do I become an early tester?", a:"Just use it — free testnet tokens from the faucet, no signup. Then tell us what broke, at X/Twitter @0xzackbh. Reports from outside get logged on the incident page, with credit."},
    {q:"Is there a token?", a:"No token has launched, and we're not rushing one. A token only makes sense when real volume justifies it — launching before there's utility is a common trap. Our leaderboard deliberately promises no allocation whatsoever. Focus now: fair fees (100% to LPs) and sustainability from ecosystem support."},
    {q:"Is Freesia Sharia-compliant?", a:"Freesia is designed on the principle of avoiding riba: yield comes from fees on real swap activity, not interest on loans, and we commit to not adding interest-based lending. But honestly — we have NOT been reviewed by any fiqh authority, so we don't call ourselves 'Sharia-certified'. Some scholars also still debate the status of AMM liquidity provision. What we offer is design principles you can verify yourself, and an open invitation for scholars of fiqh muamalah to review our contracts. For personal decisions, consult an expert you trust."},
    {q:"What is the AI Vault?", a:"The AI Vault is an experimental ERC-4626 prototype where an AI agent computes liquidity allocation strategy. Still in testnet: the code is open, but not audited and unproven in real markets. May change completely or be removed at any time. Do not treat this as a finished product."},
  ],
};

var STEPS = [
  {n:"1", ic:"🔗", t:{id:"Sambungkan Wallet",en:"Connect Wallet"},
   d:{id:"Buka DEX, tap Connect Wallet. Anda otomatis diarahkan ke jaringan LitVM Testnet. Belum punya token testnet? Klaim gratis lewat tombol Faucet (🚰) di pojok kanan atas.",en:"Open the DEX, tap Connect Wallet. You'll be automatically switched to LitVM Testnet. No testnet tokens yet? Claim them free via the Faucet button (🚰) in the top right."}},
  {n:"2", ic:"💧", t:{id:"Tambah Likuiditas",en:"Add Liquidity"},
   d:{id:"Ke tab Pool. Isi jumlah USDC dan DAI dengan nilai seimbang, lalu tap Add Liquidity. Setujui Approve untuk kedua token, baru konfirmasi transaksinya.",en:"Go to the Pool tab. Enter balanced amounts of USDC and DAI, then tap Add Liquidity. Approve both tokens, then confirm the transaction."}},
  {n:"3", ic:"🌱", t:{id:"Stake & Klaim",en:"Stake & Claim"},
   d:{id:"Ke tab Earn. LP Anda muncul di Available. Tap MAX lalu Stake LP. Reward FREE mulai terkumpul, dan bisa diklaim kapan saja.",en:"Go to the Earn tab. Your LP appears under Available. Tap MAX then Stake LP. FREE rewards start accruing and can be claimed anytime."}},
];

var TIPS = {
  id:[
    "Add Liquidity butuh DUA tanda tangan: Approve dulu, baru transaksi Add Liquidity. Keduanya harus dikonfirmasi.",
    "Isi kedua token dengan nilai seimbang sesuai rasio pool, agar tidak ada sisa yang dikembalikan.",
    "Setelah transaksi sukses, tunggu beberapa detik lalu muat ulang halaman kalau saldo LP belum berubah.",
    "Pastikan Anda punya sedikit zkLTC untuk gas.",
    "Ini testnet — gunakan token testnet, jangan dana sungguhan.",
  ],
  en:[
    "Add Liquidity needs TWO signatures: Approve first, then the Add Liquidity transaction. Both must be confirmed.",
    "Enter balanced amounts matching the pool ratio, so nothing gets refunded.",
    "After a successful transaction, wait a few seconds and refresh if your LP balance hasn't updated.",
    "Make sure you hold a little zkLTC for gas.",
    "This is testnet — use testnet tokens, never real funds.",
  ],
};

var CONTRACTS = [
  {key:"POOL",         label:{id:"Pool USDC/DAI",en:"USDC/DAI Pool"},        sub:{id:"Generasi awal · pra-V3",en:"Early generation · pre-V3"}, flag:true},
  {key:"POOL_KOPDES",  label:{id:"Pool KOPDES/USDC",en:"KOPDES/USDC Pool"},  sub:{id:"SimpleLiquidityPoolV3",en:"SimpleLiquidityPoolV3"}},
  {key:"POOL_MBGUSDC", label:{id:"Pool MBG/USDC",en:"MBG/USDC Pool"},        sub:{id:"SimpleLiquidityPoolV3",en:"SimpleLiquidityPoolV3"}},
  {key:"STAKING",      label:{id:"Kontrak Staking",en:"Staking Contract"},   sub:{id:"Earn / Farm · pool USDC/DAI",en:"Earn / Farm · USDC/DAI pool"}},
  {key:"FREE",         label:{id:"Token Reward",en:"Reward Token"},          sub:{id:"FREE",en:"FREE"}},
  {key:"USDC",         label:{id:"Token USDC",en:"USDC Token"},              sub:{id:"USDC",en:"USDC"}},
  {key:"DAI",          label:{id:"Token DAI",en:"DAI Token"},                sub:{id:"DAI",en:"DAI"}},
];

/* ===== VAULT DATA ===== */
var VAULT = {
  badge_exp:  {id:"Eksperimen Testnet", en:"Testnet Experiment"},
  badge_open: {id:"Transparan & On-Chain", en:"Transparent & On-Chain"},
  title:      {id:"AI Liquidity Vault", en:"AI Liquidity Vault"},
  lead:       {id:"Prototipe vault ERC-4626 tempat strategi alokasi dihitung oleh agen AI. Masih fase awal — kode tersedia untuk diperiksa, tapi belum diaudit dan belum terbukti di pasar nyata.",
               en:"An ERC-4626 vault prototype where allocation strategy is computed by an AI agent. Still early stage — code is open for inspection, but not audited and unproven in real markets."},
  points: [
    {id:"Setor aset, terima share standar ERC-4626 — deposit dan tarik kapan saja.", en:"Deposit assets, receive standard ERC-4626 shares — deposit and withdraw anytime."},
    {id:"Setiap keputusan AI tercatat on-chain, bukan kotak hitam.", en:"Every AI decision is logged on-chain, not a black box."},
    {id:"Dana tidak bisa dikunci admin. Anda yang pegang kendali penuh.", en:"Funds cannot be locked by admin. You hold full control."},
  ],
  cta:        {id:"Lihat Prototipe", en:"View Prototype"},
  note:       {id:"Token testnet tanpa nilai nyata · belum diaudit · bisa berubah total", en:"Testnet tokens with no real value · not audited · may change completely"},
};

var I18N = {
  nav_features:["Fitur","Features"], nav_security:["Keamanan","Security"],
  nav_start:["Cara Mulai","Get Started"], nav_contracts:["Kontrak","Contracts"],
  nav_proof:["Bukti","Proof"], nav_sustain:["Keberlanjutan","Sustainability"], nav_roadmap:["Roadmap","Roadmap"],
  nav_syariah:["Syariah","Sharia"], nav_vault:["Vault","Vault"],
  sy_badge:["Prinsip Desain","Design Principle"],
  sy_title:["Dirancang dengan Prinsip Syariah","Designed on Sharia Principles"],
  sy_sub:["Keuangan Islam tidak melarang keuntungan — ia melarang keuntungan yang tidak adil: bunga atas pinjaman (riba), spekulasi berlebihan (gharar), dan judi (maysir). Freesia dibangun dengan prinsip-prinsip itu sejak awal. Ini keputusan desain yang bisa Anda periksa sendiri, bukan sertifikasi.","Islamic finance doesn't forbid profit — it forbids unjust profit: interest on loans (riba), excessive speculation (gharar), and gambling (maysir). Freesia was built on these principles from the start. This is a design decision you can verify yourself, not a certification."],
  sy_1_t:["Fee dari Aktivitas, Bukan Bunga","Fees from Activity, Not Interest"],
  sy_1_d:["Imbal hasil penyedia likuiditas datang dari fee 0,3% atas swap nyata yang difasilitasi — aktivitas ekonomi produktif, bukan bunga tetap atas pinjaman (riba). Sumber pendapatannya bisa Anda verifikasi on-chain.","Liquidity providers' returns come from the 0.3% fee on real swaps facilitated — productive economic activity, not fixed interest on loans (riba). The source of yield is verifiable on-chain."],
  sy_2_t:["Tanpa Lending Berbunga","No Interest-Based Lending"],
  sy_2_d:["Kami berkomitmen tidak menambahkan produk pinjam-meminjam berbasis bunga ke Freesia. Model yang dilarang riba tidak akan masuk roadmap kami — itu batas desain, bukan sekadar preferensi.","We commit to not adding interest-based lending to Freesia. Riba-based models will not enter our roadmap — that's a design boundary, not just a preference."],
  sy_3_t:["Tanpa Spekulasi Buatan","No Manufactured Speculation"],
  sy_3_d:["Tidak ada token yang diluncurkan, tidak ada janji airdrop, tidak ada mekanika mirip judi untuk memancing hype. Leaderboard kami sengaja tidak menjanjikan alokasi apa pun.","No token launched, no airdrop promises, no gambling-like mechanics to bait hype. Our leaderboard deliberately promises no allocation whatsoever."],
  sy_honest_t:["Sejujurnya: ini prinsip desain, belum sertifikasi","Honestly: this is a design principle, not a certification"],
  sy_honest_d:["Freesia <strong>belum ditinjau oleh otoritas fiqih mana pun</strong>, dan sebagian ulama masih memperdebatkan status penyediaan likuiditas AMM. Kami tidak menyebut Freesia "bersertifikat syariah" karena itu klaim yang belum bisa kami buktikan. Yang bisa kami tunjukkan adalah prinsip desain di atas — dan kami <strong>mengundang ahli fiqih muamalah untuk meninjau kontrak kami</strong>. Untuk keputusan pribadi soal kepatuhan, konsultasikan dengan ahli yang Anda percaya.","Freesia <strong>has not been reviewed by any fiqh authority</strong>, and some scholars still debate the status of AMM liquidity provision. We do not call Freesia "Sharia-certified" because that's a claim we can't yet back. What we can show is the design principles above — and we <strong>invite scholars of fiqh muamalah to review our contracts</strong>. For personal compliance decisions, consult an expert you trust."],
  proof_badge:["Bukti","Proof"],
  proof_title:["Jangan Percaya. Periksa.","Don't Trust. Verify."],
  proof_sub:["Setiap proyek DeFi mengaku transparan. Dua halaman ini membuat klaim itu bisa diuji — oleh siapa pun, tanpa izin kami.","Every DeFi project claims transparency. These two pages make that claim testable — by anyone, without our permission."],
  proof_v_t:["Halaman Verifikasi","Verification Page"],
  proof_v_d:["Browser Anda sendiri menghubungi RPC LitVM dan memeriksa 19 kontrak satu per satu, langsung di depan mata: cadangan pool, suplai token, harga oracle. Tidak lewat server kami. Halaman itu juga memuat daftar hal yang <em>tidak</em> bisa dibuktikannya.","Your own browser contacts the LitVM RPC and checks 19 contracts one by one, right in front of you: pool reserves, token supplies, oracle prices. Never through our servers. That page also lists what it <em>cannot</em> prove."],
  proof_v_cta:["Periksa sendiri →","Check it yourself →"],
  proof_l_t:["Catatan Insiden","Incident Log"],
  proof_l_d:["Daftar kesalahan kami sendiri: kontrak yang harus dibuang, klaim yang dulu terlalu jauh, kelemahan keamanan yang kami temukan sendiri — termasuk satu yang <strong>masih terbuka</strong>. Tiap entri menyebut apa akibatnya, bukan cuma "sudah diperbaiki".","Our own list of mistakes: contracts we had to discard, a claim that once reached too far, a security weakness we found ourselves — including one that's <strong>still open</strong>. Each entry says what it cost, not just that it was fixed."],
  proof_l_cta:["Baca kesalahan kami →","Read our mistakes →"],
  proof_note:["Kami menerbitkan kesalahan bukan karena bangga, tapi karena DEX yang menyembunyikan kesalahannya adalah DEX yang belum ketahuan.","We publish mistakes not out of pride, but because a DEX that hides its mistakes is just a DEX that hasn't been caught yet."],
  live_badge:["Data Langsung","Live Data"],
  live_title:["Statistik On-Chain","On-Chain Statistics"],
  live_note:["Dibaca langsung dari smart contract oleh browser Anda.","Read directly from the smart contracts by your browser."],
  live_fail:["Tidak bisa menghubungi RPC LitVM. Mungkin jaringan Anda, mungkin RPC-nya sedang turun — dua-duanya berarti angka di bawah belum terbukti.","Couldn't reach the LitVM RPC. Might be your network, might be the RPC being down — either way, the numbers below aren't proven yet."],
  dia_badge:["Harga terverifikasi oleh DIA — oracle resmi LitVM","Prices verified by DIA — LitVM's official oracle"],
  ls_tvl:["Likuiditas USDC/DAI","USDC/DAI Liquidity"],
  ls_tvl_s:["dua stablecoin, ≈ USD","two stablecoins, ≈ USD"],
  ls_lp:["Total LP Supply","Total LP Supply"],
  ls_lp_s:["pool USDC/DAI","USDC/DAI pool"],
  ls_pools:["Pool Aktif","Active Pools"],
  ls_pools_s:["punya likuiditas","with liquidity"],
  ls_staked:["LP Di-stake","LP Staked"],
  ls_staked_s:["menghasilkan FREE","earning FREE"],
  ls_foot:["Angka di atas hanya sebagian. Rincian tiap kontrak — dan pemeriksaannya secara langsung — ada di halaman verifikasi.","These numbers are only part of the picture. Every contract — and a live check of each — is on the verification page."],
  start_badge:["Panduan","Guide"],
  start_title:["Cara Mulai dalam 3 Langkah","Get Started in 3 Steps"],
  start_sub:["Dari nol sampai menghasilkan reward FREE. Butuh beberapa menit saja.","From zero to earning FREE rewards. Takes just a few minutes."],
  start_cta:["Mulai Sekarang","Start Now"],
  tips_title:["Tips Penting","Important Tips"],
  con_badge:["Transparansi","Transparency"],
  con_title:["Kontrak & Jaringan","Contracts & Network"],
  con_sub:["Semua kontrak terbuka untuk diperiksa. Jangan percaya, verifikasi sendiri.","All contracts are open for inspection. Don't trust, verify."],
  con_net:["Jaringan","Network"],
  con_legacy:["Pool ini di-deploy sebelum SimpleLiquidityPoolV3 ada dan kode sumbernya hilang — sebagian proteksi tidak dapat kami verifikasi. Migrasinya tercatat terbuka di catatan insiden.","This pool was deployed before SimpleLiquidityPoolV3 existed and its source is lost — some protections can't be verified. Its migration is logged openly in the incident log."],
  con_verify_cta:["Periksa semua kontrak secara langsung","Check every contract live"],
  con_warn:["⚠️ Ini masih fase testnet. Kontrak belum diaudit pihak ketiga. Jangan gunakan dana sungguhan.","⚠️ This is still testnet. Contracts are not third-party audited. Do not use real funds."],
  hero_badge:["Testnet Live · LitVM","Testnet Live · LitVM"],
  hero_h1a:["DEX Sederhana yang","A Simple DEX That"],
  hero_h1b:["Benar-Benar Berjalan","Actually Works"],
  hero_sub:["Freesia DEX adalah AMM ringan di LitVM: swap token, sediakan likuiditas, dan stake LP untuk reward FREE. Semua on-chain, semua bisa diverifikasi.","Freesia DEX is a lightweight AMM on LitVM: swap tokens, provide liquidity, and stake LP for FREE rewards. All on-chain, all verifiable."],
  btn_launch:["Launch App","Launch App"], btn_enter:["Masuk ke App","Enter App"], btn_docs:["Baca Dokumentasi","Read Documentation"],
  btn_verify:["Periksa Kontraknya","Verify the Contracts"],
  st1l:["Fase","Phase"], st1v:["Testnet","Testnet"], st1s:["Pengembangan aktif","Active Development"],
  st2l:["Pengembang","Developer"], st2s:["Open source & transparan","Open source & transparent"],
  st3l:["Arsitektur","Architecture"],
  feat_badge:["Fitur","Features"], feat_title:["Yang Bisa Anda Lakukan","What You Can Do"],
  feat_sub:["Semuanya sudah berjalan di testnet hari ini — kecuali satu yang kami tandai jujur sebagai "segera".","Everything here runs on testnet today — except one, which we honestly label "soon"."],
  tok_title:["Model","A"], tok_title2:["Keberlanjutan","Sustainable Model"],
  tok_sub:["Bagaimana Freesia bertahan tanpa mengorbankan pengguna. Fokus pada fee yang adil dan dukungan ekosistem — bukan mencetak token untuk hype.","How Freesia sustains itself without sacrificing users. Focused on fair fees and ecosystem support — not minting a token for hype."],
  sus_fee_now:["Fee swap saat ini","Current swap fee"],
  sus_fee_future:["Protocol fee (masa depan)","Protocol fee (future)"],
  sus_max:["maks 1/6","max 1/6"],
  sus_off:["Dimatikan default. LP selalu dapat minimal 5/6 fee.","Off by default. LPs always get at least 5/6 of fees."],
  sus_treasury:["Sumber treasury awal","Early treasury source"],
  sus_eco:["Ekosistem","Ecosystem"],
  sus_grant:["Grant & kredit audit LitVM — bukan fee pengguna.","LitVM grants & audit credits — not user fees."],
  road_title:["Jalan Menuju Mainnet","The Road to Mainnet"],
  sec_badge:["Keamanan","Security"], sec_title:["Keamanan Sejak Hari Pertama","Security from Day One"],
  dev_badge:["Dari Pengembang","From the Developer"],
  dev_title:["Dibangun dengan","Built with"], dev_heart:["Hati","Heart"], dev_title2:[", Bukan Modal Besar",", Not Big Capital"],
  dev_p1:["Freesia DEX adalah proyek solo yang saya bangun dari nol di atas LitVM. Setiap baris kode, desain, dan keputusan berasal dari pengalaman saya sendiri sebagai trader DeFi yang frustrasi dengan fitur dasar yang masih hilang di DEX besar.","Freesia DEX is a solo project I built from scratch on LitVM. Every line of code, every design, and every decision comes from my own experience as a DeFi trader frustrated with basic features still missing from major DEXes."],
  dev_p2:["Saat ini kami di fase testnet. Tidak ada angka TVL yang dibesar-besarkan, tidak ada testimonial palsu — hanya kode nyata yang terus berkembang. Saya membangun satu orang, jadi kesalahan pasti terjadi; yang bisa saya janjikan bukan kesempurnaan, tapi Anda akan selalu tahu.","We're in testnet phase. No inflated TVL, no fake testimonials — just real code that keeps evolving. I build alone, so mistakes will happen; what I can promise isn't perfection, but that you'll always know."],
  dev_p3:['"Kalau kamu percaya pada visi DEX yang benar-benar user-first, bergabunglah sebagai early tester. Feedback-mu akan membentuk fitur-fitur berikutnya."','"If you believe in the vision of a truly user-first DEX, join as an early tester. Your feedback will shape the next features."'],
  dev_role:["Pengembang Solo & Pendiri","Solo Developer & Founder"],
  faq_badge:["Pertanyaan Umum","FAQ"],
  cta_title:["Siap Mencobanya?","Ready to Try It?"],
  cta_sub:["Token testnet gratis lewat faucet, tanpa daftar, tanpa izin. Kalau ada yang salah, beri tahu kami — itu justru gunanya fase ini.","Free testnet tokens from the faucet, no signup, no permission. If something's wrong, tell us — that's exactly what this phase is for."],
  foot_desc:["AMM ringan di LitVM yang memperingatkan Anda sebelum rugi. Semua on-chain, semua bisa diperiksa sendiri.","A lightweight AMM on LitVM that warns you before you lose money. All on-chain, all verifiable yourself."],
  foot_product:["Produk","Product"], foot_res:["Sumber Daya","Resources"], foot_docs:["Dokumentasi","Documentation"], foot_comm:["Komunitas","Community"],
  foot_verify:["Verifikasi kontrak","Verify contracts"], foot_log:["Catatan insiden","Incident log"],
  foot_report:["Laporkan masalah","Report an issue"],
  foot_copy:["© 2026 Freesia DEX. Dibangun dengan transparansi untuk komunitas DeFi.","© 2026 Freesia DEX. Built with transparency for the DeFi community."],
};
